#!/usr/bin/env bash
# agents-to-opencode.sh — convert the role contracts in agents/ into
# OpenCode-native agent files (https://opencode.ai/docs/agents/).
#
# Bash, not JS, because everything in this repo that executes is bash — the
# JS shim exists only where OpenCode's plugin API leaves no choice.
#
# The mapping is mechanical, per docs/consume-opencode.md:
#   description        -> carried over verbatim (required by OpenCode)
#   name               -> dropped (the filename is the agent's name, in both
#                         systems; OpenCode documents no `name` field)
#   model: inherit     -> dropped (not a valid OpenCode provider/model id;
#                         omitting `model` is how OpenCode inherits)
#   mode: subagent     -> added (these contracts are delegation targets)
#   disallowedTools    -> a denylist containing Edit becomes
#                         `permission: edit: deny` — OpenCode has no separate
#                         write/edit split, so the harness's two denylist
#                         tiers collapse into one (the roles that file their
#                         own documents lose a little reach in exchange for a
#                         boundary the runtime holds)
#   body               -> untouched, byte for byte
#
# Behavior:
#   - reads <source>/**/*.md (default: the agents/ directory next to this
#     script's parent), skipping README.md and any file whose name starts
#     with `_` (scaffolding, wherever it lives)
#   - writes one flat file per role into TARGET_DIR (OpenCode resolves the
#     agent name from the filename); never writes anywhere else
#   - refuses to overwrite an existing file unless --force is given
#   - idempotent: same inputs, same outputs, every run
#   - prints every file it writes; a role missing `description:` is an
#     error (OpenCode requires it), reported and counted, never guessed at
#
# Usage:
#   scripts/agents-to-opencode.sh [--force] [--source DIR] TARGET_DIR
#   scripts/agents-to-opencode.sh .opencode/agents
#
# Exit codes: 0 = all converted; 1 = usage error or at least one file
# skipped (existing without --force, or missing description).

set -euf

usage() {
  echo "usage: $0 [--force] [--source DIR] TARGET_DIR" >&2
  exit 1
}

force=0
src=""
target=""
while [ $# -gt 0 ]; do
  case "$1" in
    --force) force=1 ;;
    --source) shift; [ $# -gt 0 ] || usage; src="$1" ;;
    -h|--help) usage ;;
    -*) echo "$0: unknown option '$1'" >&2; usage ;;
    *) [ -n "$target" ] && usage; target="$1" ;;
  esac
  shift
done
[ -n "$target" ] || usage

# Default source: the agents/ directory in the repo this script ships in.
if [ -z "$src" ]; then
  script_dir="$(cd "$(dirname "$0")" && pwd)"
  src="$script_dir/../agents"
fi
[ -d "$src" ] || { echo "$0: source directory not found: $src" >&2; exit 1; }

mkdir -p "$target"
src_abs="$(cd "$src" && pwd)"
target_abs="$(cd "$target" && pwd)"
if [ "$src_abs" = "$target_abs" ]; then
  echo "$0: target must not be the source directory" >&2
  exit 1
fi

wrote=0
skipped=0
failed=0

# Sorted for deterministic output ordering run to run.
for f in $(find "$src_abs" -name '*.md' ! -name 'README.md' ! -name '_*' | LC_ALL=C sort); do
  base="$(basename "$f")"
  out="$target_abs/$base"          # basename only: never outside target
  rel="${f#"$src_abs"/}"

  if [ -e "$out" ] && [ "$force" -ne 1 ]; then
    echo "skip  $out exists (use --force to overwrite)" >&2
    skipped=$((skipped + 1))
    continue
  fi

  if ! awk -v rel="$rel" '
    BEGIN { fm = 0; deny = 0; desc = "" }
    /^---[[:space:]]*$/ {
      fm++
      if (fm == 1) next
      if (fm == 2) {
        if (desc == "") exit 3   # description is required by OpenCode
        print "---"
        print "# generated by scripts/agents-to-opencode.sh from agents/" rel
        print "# edit the source contract and re-run; do not hand-edit"
        print desc
        print "mode: subagent"
        if (deny) {
          print "permission:"
          print "  edit: deny"
        }
        print "---"
        next
      }
    }
    fm == 1 {
      if ($0 ~ /^description:/) desc = $0
      if ($0 ~ /^disallowedTools:/ && $0 ~ /Edit/) deny = 1
      next
    }
    fm >= 2 { print }
  ' "$f" > "$out.tmp"; then
    rm -f "$out.tmp"
    echo "FAIL  $rel: no description: in frontmatter (OpenCode requires one) — not converted" >&2
    failed=$((failed + 1))
    continue
  fi
  mv "$out.tmp" "$out"
  echo "wrote $out"
  wrote=$((wrote + 1))
done

echo "done: $wrote written, $skipped skipped, $failed failed"
[ "$skipped" -eq 0 ] && [ "$failed" -eq 0 ]
